replicaCount: 1
service:
    type: NodePort
ingress:
  enabled: true
  className: "alb"
  hosts:
    - host: "${host}"
      paths:
        - path: /
          pathType: ImplementationSpecific
  annotations:
        kubernetes.io/ingress.class: alb
        alb.ingress.kubernetes.io/scheme: internet-facing
        service.beta.kubernetes.io/aws-load-balancer-type: alb
        alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}]'

  